;;;###autoload
(defun fdx/refactoring/extract-let ()
  "Extract a let from an assignment"
  (interactive)
  (save-excursion
    (beginning-of-line)
    (forward-word)
    (backward-word)
    (insert "let(:")
    (search-forward "=")
    (delete-backward-char 1)
    (insert " ")
    (backward-word)
    (forward-word)
    (insert ")")
    (forward-char)
    (insert "{ ")
    (end-of-line)
    (insert " }")
    (beginning-of-line)
    (forward-word)
    (backward-word)
    (while (search-forward-regexp " +" (line-end-position) t)
      (replace-match " " nil nil)
      )))
