;; Ruby
(add-to-list 'auto-mode-alist '("Rakefile\\'"         . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake\\'"          . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru\\'"            . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile\\'"          . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.gemspec\\'"       . ruby-mode))
(add-to-list 'auto-mode-alist '("Guardfile\\'"        . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rabl\\'"          . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.env\\'"           . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.coffee\\.erb\\'"  . coffee-mode))
(add-to-list 'auto-mode-alist '("\\.js\\.erb\\'"      . javascript-mode))
